### ISSUE TITLE
유저 추가 정보 설정하기

### ISSUE THREAD

**Issue by jiaeYoon** [jiaeYoon/Booklog#33]
## Description
최초 소셜 로그인 시, 사용할 닉네임을 입력받고 역할(role)을 GUEST에서 USER로 변경

( 1 ) 소셜 로그인에 성공하면 user.nickname을 확인 
( 2-1 ) nickname이 없다면 nickname 설정 Modal 띄움 -> 중복 nickname 검사 후 role을 변경하며 설정 완료
( 2-2 ) nickname이 있다면 바로 홈 화면 접속

## Todo
- [x] nickname 설정 로직 구현
- [x] nickname 설정 후, sessionUser 객체의 nickname 필드 업데이트하기
- [x] 닉네임 입력받을 부트스트랩 Modal 띄우기

## ETC
기타 사항을 작성하세요
